import "./css/style.css";
import { Inter } from "next/font/google";
import BubbleBackground from "@/components/ui/bubble";
import FloatingContact from "@/components/foldercomponent"; // Добавьте импорт

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${inter.variable} bg-gray-50 font-inter tracking-tight text-gray-900 antialiased`}
      >
        {/* Фоновая анимация */}
        <BubbleBackground />

        <div className="relative z-10 flex min-h-screen flex-col overflow-hidden supports-[overflow:clip]:overflow-clip">
          {children}
        </div>

        {/* Фиксированная кнопка & окно "Связаться со мной" */}
        <FloatingContact />
      </body>
    </html>
  );
}